repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "-l=120"
          - "--multi-line=3"
          - "--tc"
          - "--up"
          - "--force-grid-wrap=0"
          - "--profile=black"
        exclude: >
          (?x)^(
            alembic/.+
          )$

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - "--expand-star-imports"
          - "--remove-all-unused-imports"
          - "--ignore-init-module-imports"
          - "--recursive"
          - "--in-place"
        exclude: >
          (?x)^(
            alembic/.+
          )$

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - "-l 120"
        exclude: >
          (?x)^(
            alembic/.+
          )$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
        args:
          - "--max-line-length=120"
          - "--extend-ignore=E203,B008,F405,F401,B006,B010"
        exclude: >
          (?x)^(
            alembic/.+
          )$
