image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 4096
  steps:
  - step: &build
      size: 2x
      name: Build
      services:
        - docker
      caches:
        - docker
      script:
        - docker build -t $IMAGE_NAME:$BITBUCKET_TAG .
        - docker login -u $SCW_REGISTRY_USERNAME -p $SCW_REGISTRY_PASSWORD $SCW_REGISTRY
        - docker push $IMAGE_NAME:$BITBUCKET_TAG

pipelines:
  tags:
    '**':
      - step: *build