channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=22.3.1
  - fastapi=0.86.0
  - sqlmodel=0.0.8
  - alembic=1.8.1
  - greenlet=2.0.1
  - email-validator=1.3.0
  - alembic=1.8.1
  - httpx=0.23.0
  - orjson=3.8.1
  - inflection=0.5.1
  - python-keycloak=2.6.0
  - python-dateutil=2.8.2
  - python-jose=3.3.0
  - python-multipart=0.0.5
  - passlib=1.7.4
  - psycopg2-binary=2.9.3
  - asyncpg=0.27.0
  - aioredis=2.0.1
  - minio=7.1.12
  - pillow=9.2.0
  - pip:
    - fastapi-pagination==0.11.1
    - apscheduler==4.0.0a2
    - hypercorn==0.14.3
    - bcrypt==4.0.1
