channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=22.3.1
  - python-dotenv=0.21.0
  - fastapi=0.89.1
  - alembic=1.9.1
  - email-validator=1.3.0
  - httpx=0.23.3
  - orjson=3.8.5
  - inflection=0.5.1
  - python-dateutil=2.8.2
  - python-jose=3.3.0
  - python-multipart=0.0.5
  - passlib=1.7.4
  - psycopg2-binary=2.9.3
  - asyncpg=0.27.0
  - redis-py=4.4.2
  - minio=7.1.13
  - pillow=9.4.0
  - pip:
    - sqlmodel==0.0.8
    - uuid6==2022.10.25
    - fastapi-pagination==0.11.1
    - apscheduler==4.0.0a2
    - hypercorn==0.14.3
    - bcrypt==4.0.1
