channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.3.1
  - fastapi=0.86.0
  - email-validator=1.3.0
  - sqlalchemy=1.4.44
  - alembic=1.8.1
  - httpx=0.23.0
  - orjson=3.8.1
  - psycopg2-binary=2.9.3
  - inflection=0.5.1
  - python-keycloak=2.6.0
  - python-dateutil=2.8.2
  - pip:
    - sqlservice==1.3.0
    - hypercorn==0.14.3
    - sqlalchemy-json==0.5.0
