version: "3"

volumes:
  data:
  auth:
services:
  redis:
    container_name: redis
    image: "redis:alpine3.17"
    restart: always
    ports:
      - 6379:6379
  dbauth:
    image: postgres:14.0
    container_name: dbauth
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth
    volumes:
      - auth:/var/lib/pgsql
    ports:
      - 54320:5432
  dbdata:
    image: postgres:14.0
    container_name: dbdata
    environment:
      - POSTGRES_USER=data
      - POSTGRES_PASSWORD=data
      - POSTGRES_DB=data
    volumes:
      - data:/var/lib/pgsql
    ports:
      - 54322:5432
  worker:
    image: rg.fr-par.scw.cloud/bib-batteries/bib-worker:1.1.3
    container_name: worker
    command: "alembic upgrade heads"
    environment:
    - DB_MIGRATE=true
    - DB_DATA_HOST=dbdata
    - DB_DATA_PORT=5432
    - S3_KEY=key
    - S3_SECRET=secert
    - S3_BUCKET=bucket
    depends_on:
      dbdata:
        condition: service_started
  api:
    build:
      context: .
    container_name: api
    environment:
    - DB_MIGRATE=true
    - DB_INIT=true
    - DB_AUTH_HOST=dbauth
    - DB_AUTH_PORT=5432
    - DB_DATA_HOST=dbdata
    - DB_DATA_PORT=5432
    - REDIS_HOST=redis
    - LOG_LEVEL=INFO
    - ACCESSLOG=true
    - ERRORLOG=true
    - RELOAD=true
    - FIRST_SUPERUSER_EMAIL=admin@bib.fr
    - FIRST_SUPERUSER_PASSWORD=password
    depends_on:
      worker:
        condition: service_completed_successfully
      redis:
        condition: service_started
      dbdata:
        condition: service_started
      dbauth:
        condition: service_started
    ports:
      - 8000:8000
