version: "3"

volumes:
  data:
services:
  redis:
    container_name: redis
    image: "redis:7-alpine3.17"
    restart: always
    ports:
      - 6379:6379
  dbdata:
    image: postgres:14.0
    container_name: dbdata
    environment:
      - POSTGRES_USER=data
      - POSTGRES_PASSWORD=data
      - POSTGRES_DB=data
    volumes:
      - data:/var/lib/pgsql
    ports:
      - 5432:5432
  api:
    build:
      context: .
    container_name: api
    environment:
    - DB_MIGRATE=true
    - DB_INIT=true
    - DB_HOST=dbdata
    - DB_PORT=5432
    - REDIS_HOST=redis
    - LOG_LEVEL=INFO
    - ACCESSLOG=true
    - ERRORLOG=true
    - RELOAD=true
    - FIRST_SUPERUSER_EMAIL=admin@fast.api
    - FIRST_SUPERUSER_PASSWORD=password
    depends_on:
      redis:
        condition: service_started
      dbdata:
        condition: service_started
    ports:
      - 8000:8000
