version: "3"

volumes:
  data:
services:
  redis:
    container_name: redis
    image: redis:7-alpine3.18
    restart: always
    ports:
      - 6379:6379
  pgsql:
    container_name: pgsql
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - data:/var/lib/pgsql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
    container_name: api
    environment:
      - DB_MIGRATE=true
      - DB_INIT=true
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=data
      - REDIS_HOST=redis
      - LOG_LEVEL=info
      - ACCESSLOG=true
      - FIRST_SUPERUSER_EMAIL=admin@fast.api
      - FIRST_SUPERUSER_PASSWORD=password
      - DYNAMICS_PUBLIC_KEY_FILE=./src/dynamics.pub
    depends_on:
      redis:
        condition: service_started
      pgsql:
        condition: service_healthy
    ports:
      - 8000:8000
