version: "3"

volumes:
  data:
  auth:
services:
  redis:
    container_name: redis
    image: "redis:alpine3.17"
    restart: always
    ports:
      - 6379:6379
  dbauth:
    image: postgres:14.0
    container_name: dbauth
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth
    volumes:
      - auth:/var/lib/pgsql
    ports:
      - 54320:5432
  dbdata:
    image: postgres:14.0
    container_name: dbdata
    environment:
      - POSTGRES_USER=data
      - POSTGRES_PASSWORD=data
      - POSTGRES_DB=data
    volumes:
      - data:/var/lib/pgsql
    ports:
      - 54322:5432
  api:
    build:
      context: .
    container_name: api
    environment:
    - DB_MIGRATE=true
    - DB_INIT=true
    - DB_AUTH_HOST=dbauth
    - DB_DATA_HOST=dbdata
    - REDIS_HOST=redis
    - LOG_LEVEL=INFO
    - ACCESSLOG=true
    - ERRORLOG=true
    - RELOAD=true
    - FIRST_SUPERUSER_EMAIL=admin@bib.fr
    - FIRST_SUPERUSER_PASSWORD=password
    depends_on:
      - redis
      - dbdata
      - dbauth
      - dbsched
    ports:
      - 8000:8000
