version: "3"

volumes:
  data:
  cache:
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=bib
      - MYSQL_PASSWORD=bib
      - MYSQL_DATABASE=bib
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:6-alpine
    container_name: redis
    volumes:
      - cache:/data
    ports:
      - 6379:6379
  api:
    build:
      context: .
    container_name: api
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    ports:
      - 8000:8000