version: "3"

volumes:
  data:
  cache:
services:
  pgsql:
    image: postgres:14.0
    container_name: pgsql
    environment:
      - POSTGRES_USER=bib
      - POSTGRES_PASSWORD=bib
      - POSTGRES_DB=bib
    volumes:
      - data:/var/lib/pgsql
    ports:
      - 5432:5432
  api:
    build:
      context: .
    container_name: api
    env_file:
      - .env
    depends_on:
      - pgsql
    ports:
      - 8000:8000