"""create

Revision ID: cfb9b8a064f2
Revises: 
Create Date: 2022-12-14 10:30:37.141311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'cfb9b8a064f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_cell',
    sa.Column('attachements', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('technology', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('nominal_capacity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battery_model',
    sa.Column('size', sa.JSON(), nullable=True),
    sa.Column('attachements', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('nominal_capacity', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Integer(), nullable=True),
    sa.Column('number_cells', sa.Integer(), nullable=True),
    sa.Column('configuration', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('cells_model', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('siliconned', sa.Boolean(), nullable=True),
    sa.Column('charger', sa.Boolean(), nullable=True),
    sa.Column('communicaing', sa.Boolean(), nullable=True),
    sa.Column('diag_tool', sa.Boolean(), nullable=True),
    sa.Column('msds_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('un38_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battery_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['battery_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_info')
    op.drop_table('battery_state_value')
    op.drop_table('battery_model')
    op.drop_table('battery_cell')
    # ### end Alembic commands ###
