"""entities

Revision ID: 71d42dfc6cd3
Revises: 18ebb8d904c6
Create Date: 2022-12-13 23:43:39.687402

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '71d42dfc6cd3'
down_revision = '18ebb8d904c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_job = op.create_table('user_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    company = op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    user = op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('fleet', sa.JSON(), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['user_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        user_job,
        [
            {
                "id": 1,
                "name": "manager",
            },
            {
                "id": 2,
                "name": "operator",
            },
            {
                "id": 3,
                "name": "repairer",
            },
            {
                "id": 4,
                "name": "secondlife",
            },
            {
                "id": 5,
                "name": "recycler",
            }
        ],
    )

    op.bulk_insert(
        company,
        [
            {
                "id": 1,
                "name": "bib-batteries",
                "contact_id": 1,
            }
        ],
    )

    op.bulk_insert(
        user,
        [
            {
                "id": 1,
                "company_id": 1,
                "firstname": "admin",
                "lastname": "admin",
                "fleet": {},
                "email": "admin@bib.fr",
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_job')
    op.drop_table('company')
    # ### end Alembic commands ###
