"""company

Revision ID: a50ed95c11f3
Revises: 2b314ea29a44
Create Date: 2022-12-23 05:23:21.084154

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "a50ed95c11f3"
down_revision = "2b314ea29a44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Company",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("contact_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("created_by_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["User.id"], ondelete="set null"),
        sa.ForeignKeyConstraint(["created_by_id"], ["User.id"], ondelete="set null"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Company_id"), "Company", ["id"], unique=False)
    op.add_column("User", sa.Column("job_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("User", sa.Column("company_id", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, "User", "Company", ["company_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="foreignkey")
    op.drop_column("User", "company_id")
    op.drop_column("User", "job_title")
    op.drop_index(op.f("ix_Company_id"), table_name="Company")
    op.drop_table("Company")
    # ### end Alembic commands ###
