"""social

Revision ID: fa17073851f5
Revises: fe970ecc04c1
Create Date: 2023-10-27 13:48:48.465338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fa17073851f5'
down_revision = 'fe970ecc04c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SocialMedia',
    sa.Column('platform', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform')
    )
    op.create_index(op.f('ix_SocialMedia_id'), 'SocialMedia', ['id'], unique=False)
    op.create_table('SocialEngagement',
    sa.Column('content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reaction_date', sa.DateTime(), nullable=False),
    sa.Column('social_media_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['social_media_id'], ['SocialMedia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SocialEngagement_id'), 'SocialEngagement', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SocialEngagement_id'), table_name='SocialEngagement')
    op.drop_table('SocialEngagement')
    op.drop_index(op.f('ix_SocialMedia_id'), table_name='SocialMedia')
    op.drop_table('SocialMedia')
    # ### end Alembic commands ###
